<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="SpotMicroAI">

  <material name="yellow">
    <color rgba="0.92 0.83 0.0 1"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  <material name="grey">
    <color rgba="0.6 0.6 0.6 1"/>
  </material>

  <!-- Params -->

  <xacro:property name="body_length" value="0.140" />
  <xacro:property name="body_width" value="0.110" />
  <xacro:property name="body_height" value="0.070" />

  <xacro:property name="lidar_length" value="0.0985" />
  <xacro:property name="lidar_width" value="0.0577" />
  <xacro:property name="lidar_height" value="0.070" />


  <xacro:property name="front_length" value="0.058" />
  <xacro:property name="rear_length" value="0.040" />

  <xacro:property name="shoulder_length" value="0.044" />
  <xacro:property name="shoulder_width" value="0.038" />

  <xacro:property name="leg_length" value="0.120" />
  <xacro:property name="foot_length" value="0.115" />

  <xacro:property name="toe_radius" value="0.020" />
  <!--  <xacro:property name="toe_radius" value="0.014" /> -->
  <xacro:property name="toe_width" value="0.020" />
  <xacro:property name="shift" value="0.052" />
  <xacro:property name="shiftx" value="0.093" />
  <xacro:property name="shifty" value="0.036" />

  <!-- Macros -->
  <!-- Gazebo -->
  <xacro:include filename="$(find spotmicro_description)/config/gazebo_plugins.xacro" />
  <xacro:add_gazebo_imu_sensor link_name="base_link" frame="base_link" />
  <xacro:add_gazebo_camera pose="-${front_length + body_length/2} -0.0 -0.0 -0.0 -0.0 -0.0" xyz="-${front_length + body_length/2} -0.0 -0.0" rpy="-0.0 -0.0 -0.0" link_name="base_link" />
  <xacro:add_gazebo_depth_camera pose="-${front_length + body_length/2} -0.0 -0.0 -0.0 -0.0 -0.0" xyz="-${front_length + body_length/2} -0.0 -0.0" rpy="-0.0 -0.0 -0.0" link_name="base_link" />

  <xacro:macro name="gazebo_link_reference" params="link_name color mu1:=0.9 mu2:=0.9" >
    <gazebo reference="${link_name}">
      <mu1>${mu1}</mu1>
      <mu2>${mu2}</mu2>
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="gazebo_transmission" params="joint_name" >
    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${joint_name}_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- Links -->
  <xacro:macro name="gen_shoulder" params="name left">
    <xacro:gazebo_link_reference link_name="${name}" color="Black"/>
    <link name="${name}">
      <visual>
        <xacro:if value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/lshoulder.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.135 -0.02 -0.01"/>
        </xacro:if>
        <xacro:unless value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/rshoulder.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.135 -0.09 -0.01"/>
        </xacro:unless>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="${shoulder_length} ${shoulder_width} ${body_height}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.10"/>
        <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="gen_shoulder_joint" params="pos shiftx shifty">
    <xacro:gazebo_transmission joint_name="${pos}_shoulder"/>
    <joint name="${pos}_shoulder" type="revolute">
      <parent link="base_link"/>
      <child link="${pos}_shoulder_link"/>
      <axis xyz="1 0 0"/>
      <origin rpy="0 0 0" xyz="${shiftx} ${shifty} 0"/>
      <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.7"/>
      <dynamics damping="0.0" friction="0.5"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="gen_leg" params="name left">
    <xacro:gazebo_link_reference link_name="${name}_cover" color="Yellow"/>
    <link name="${name}_cover">
      <visual>
        <xacro:if value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/larm_cover.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.125 0.04 -0.02"/>
        </xacro:if>
        <xacro:unless value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/rarm_cover.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.125 -0.15 -0.02"/>
        </xacro:unless>
        <material name="yellow"/>
      </visual>
    </link>
    <xacro:gazebo_link_reference link_name="${name}" color="Yellow"/>
    <link name="${name}">
      <visual>
        <xacro:if value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/larm.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.125 0.04 -0.02"/>
        </xacro:if>
        <xacro:unless value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/rarm.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.125 -0.15 -0.02"/>
        </xacro:unless>
        <material name="black"/>
<!--        <geometry>
          <box size="0.028 0.036 ${leg_length}"/>
        </geometry>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 -0.050"/>
        <material name="yellow"/>-->
      </visual>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 -0.050"/>
        <geometry>
          <box size="0.028 0.036 ${leg_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.15"/>
        <inertia ixx="1000" ixy="0" ixz="0" iyy="1000" iyz="0" izz="1000" />
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="gen_leg_joint" params="pos shift">
    <xacro:gazebo_transmission joint_name="${pos}_leg"/>
    <joint name="${pos}_leg" type="revolute">
      <parent link="${pos}_shoulder_link"/>
      <child link="${pos}_leg_link"/>
      <axis xyz="0 1 0"/>
      <origin rpy="0 0 0" xyz="0 ${shift} 0"/>
      <limit effort="1000.0" lower="-2.666" upper="1.548" velocity="0.5"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <joint name="${pos}_leg_cover_joint" type="fixed">
    <parent link="${pos}_leg_link"/>
    <child link="${pos}_leg_link_cover"/>
        <origin xyz="0 0 0"/>
  </joint>
  </xacro:macro>

  <xacro:macro name="gen_foot" params="name left">
    <xacro:gazebo_link_reference link_name="${name}" color="Black"/>
    <link name="${name}">
      <visual>
        <xacro:if value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/lfoot.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.120 0.04 0.1"/>
        </xacro:if>
        <xacro:unless value="${left}">
        <geometry>
          <mesh filename="package://spotmicro_description/meshes/stl/rfoot.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.120 -0.15 0.1"/>
        </xacro:unless>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.026 0.020 ${foot_length}"/>
        </geometry>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 -0.050"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="1000" ixy="0" ixz="0" iyy="1000" iyz="0" izz="1000" />
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="gen_foot_joint" params="pos">
    <xacro:gazebo_transmission joint_name="${pos}_foot"/>
    <joint name="${pos}_foot" type="revolute">
      <parent link="${pos}_leg_link"/>
      <child link="${pos}_foot_link"/>
      <axis xyz="0 1 0"/>
      <origin rpy="0 0 0" xyz="-0.01 0 -${leg_length}"/>
      <limit effort="1000.0" lower="-0.1" upper="2.59" velocity="0.5"/>
      <dynamics damping="0.0" friction="0.5"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="gen_toe" params="name">
    <xacro:gazebo_link_reference link_name="${name}" color="Grey"/>
    <link name="${name}">
      <visual>
        <geometry>
        <mesh filename="package://spotmicro_description/meshes/stl/foot.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin rpy="0 -0.40010 0" xyz="0 -0.01 0"/>
        <material name="grey"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${toe_radius}" />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <contact_coefficients mu="1.1" />
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="1000" ixy="0" ixz="0" iyy="1000" iyz="0" izz="1000" />
      </inertial>
    </link>
  </xacro:macro>

 <xacro:macro name="gen_toe_joint" params="pos">
    <joint name="${pos}_toe" type="fixed">
      <parent link="${pos}_foot_link"/>
      <child link="${pos}_toe_link"/>
      <origin xyz="0 0 -${foot_length}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="gen_full_leg_joint" params="pos shiftx shifty shift left">
    <xacro:gen_shoulder name="${pos}_shoulder_link" left="${left}"/>
    <xacro:gen_leg name="${pos}_leg_link" left="${left}"/>
    <xacro:gen_foot name="${pos}_foot_link" left="${left}"/>
    <xacro:gen_toe name="${pos}_toe_link"/>

    <xacro:gen_shoulder_joint pos="${pos}" shiftx="${shiftx}" shifty="${shifty}"/>
    <xacro:gen_leg_joint pos="${pos}" shift="${shift}"/>
    <xacro:gen_foot_joint pos="${pos}"/>
    <xacro:gen_toe_joint pos="${pos}"/>
  </xacro:macro>

  <!-- Robot Body -->
  <xacro:gazebo_link_reference link_name="base_link" color="Black"/>
  <link name="base_link">
    <visual>
      <geometry>
        <mesh filename="package://spotmicro_description/meshes/stl/mainbody.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0 0 0" xyz="-0.045 -0.060 -0.015"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="2.80"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    </inertial>
  </link>

  <!-- Lidar Backpack -->
  <xacro:gazebo_link_reference link_name="lidar_link" color="Black"/>
   <link name="lidar_link">
    <visual>
      <geometry>
        <mesh filename="package://spotmicro_description/meshes/stl/rplidar_main.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
      <origin rpy="1.57075 0 0" xyz="${-lidar_length/2-0.015} ${lidar_width/2} 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.50"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    </inertial>
  </link>
  <joint name="base_lidar" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${body_height/2}"/>
  </joint>
  <gazebo reference="lidar_link">
      <material>Gazebo/Black</material>
      <sensor type="ray" name="lidar">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>400</samples>
              <resolution>1</resolution>
              <min_angle>${-pi}</min_angle>
              <max_angle>${pi}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.50</min>
            <max>100.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_laser.so">
          <topicname>lidar_link/scan</topicname>
          <frameName>lidar_link</frameName>
        </plugin>
      </sensor>
    </gazebo>

  <xacro:gazebo_link_reference link_name="rear_link" color="Yellow"/>
  <link name="rear_link">
    <visual>
      <geometry>
        <mesh filename="package://spotmicro_description/meshes/stl/backpart.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.040 -0.060 -0.0140"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${rear_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0.135 0 0"/>
    </collision>
    <inertial>
      <mass value="0.20"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    </inertial>
  </link>
  <joint name="base_rear" type="fixed">
    <parent link="base_link"/>
    <child link="rear_link"/>
  </joint>

  <xacro:gazebo_link_reference link_name="front_link" color="Yellow"/>
  <link name="front_link">
    <visual>
      <geometry>
        <mesh filename="package://spotmicro_description/meshes/stl/frontpart.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.040 -0.060 -0.0140"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${front_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.145 0 0"/>
    </collision>
    <inertial>
      <mass value="0.20"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    </inertial>

  </link>
  <joint name="base_front" type="fixed">
    <parent link="base_link"/>
    <child link="front_link"/>
  </joint>

  <!-- create Legs -->

  <xacro:gen_full_leg_joint pos="front_left" shiftx="-${shiftx}" shifty="-${shifty}" shift="-${shift}" left="true"/>
  <xacro:gen_full_leg_joint pos="front_right" shiftx="-${shiftx}" shifty="${shifty}" shift="${shift}" left="false"/>
  <xacro:gen_full_leg_joint pos="rear_left" shiftx="${shiftx}" shifty="-${shifty}" shift="-${shift}" left="true"/>
  <xacro:gen_full_leg_joint pos="rear_right" shiftx="${shiftx}" shifty="${shifty}" shift="${shift}" left="false"/>

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

</robot>
